export const educations = [
	{
		value: 'Primary/Secondary School/SPM/"O" Level',
		label: 'Primary/Secondary School/SPM/"O" Level',
	},
	{
		value: 'Higher Secondary/STPM/"A" Level/Pre-U',
		label: 'Higher Secondary/STPM/"A" Level/Pre-U',
	},
	{ value: 'Professional Certificate', label: 'Professional Certificate' },
	{
		value: 'Diploma/Advanced/Higher/Graduate Diploma',
		label: 'Diploma/Advanced/Higher/Graduate Diploma',
	},
	{
		value: "Bachelor's Degree/Post Graduate Diploma/Professional Degree",
		label: "Bachelor's Degree/Post Graduate Diploma/Professional Degree",
	},
	{ value: "Master's Degree", label: "Master's Degree" },
	{ value: 'Doctorate (PhD)', label: 'Doctorate (PhD)' },
];

const fieldStudiesData = [
	{
		code: 1,
		name: 'Engineering',
		children: {
			entity: 'field-of-studies',
			items: [
				{ code: 12, name: 'Engineering (Aviation/Aeronautics/Astronautics)' },
				{ code: 101, name: 'Engineering (Bioengineering/Biomedical)' },
				{ code: 13, name: 'Engineering (Chemical)' },
				{ code: 14, name: 'Engineering (Civil)' },
				{ code: 16, name: 'Engineering (Computer/Telecommunication)' },
				{ code: 18, name: 'Engineering (Electrical/Electronic)' },
				{ code: 24, name: 'Engineering (Environmental/Health/Safety)' },
				{ code: 19, name: 'Engineering (Industrial)' },
				{ code: 23, name: 'Engineering (Marine)' },
				{ code: 21, name: 'Engineering (Material Science)' },
				{ code: 20, name: 'Engineering (Mechanical)' },
				{ code: 102, name: 'Engineering (Mechatronic/Electromechanical)' },
				{
					code: 22,
					name: 'Engineering (Metal Fabrication/Tool & Die/Welding)',
				},
				{ code: 103, name: 'Engineering (Mining/Mineral)' },
				{ code: 25, name: 'Engineering (Others)' },
				{ code: 26, name: 'Engineering (Petroleum/Oil/Gas)' },
			],
		},
	},
	{
		code: 2,
		name: 'Science',
		children: {
			entity: 'field-of-studies',
			items: [
				{ code: 3, name: 'Agriculture/Aquaculture/Forestry' },
				{ code: 6, name: 'Biology' },
				{ code: 55, name: 'BioTechnology' },
				{ code: 7, name: 'Chemistry' },
				{ code: 8, name: 'Computer Science/Information Technology' },
				{ code: 104, name: 'Food Technology/Nutrition/Dietetics' },
				{ code: 11, name: 'Geographical Science' },
				{ code: 105, name: 'Geology/Geophysics' },
				{ code: 106, name: 'History' },
				{ code: 38, name: 'Mathematics' },
				{ code: 107, name: 'Optometry' },
				{ code: 108, name: 'Philosophy' },
				{ code: 46, name: 'Physics' },
				{ code: 110, name: 'Political Science' },
				{ code: 100, name: 'Quantity Survey' },
				{ code: 50, name: 'Science & Technology' },
				{ code: 113, name: 'Social Science/Sociology' },
				{ code: 114, name: 'Sports Science & Management' },
			],
		},
	},
	{
		code: 3,
		name: 'Business',
		children: {
			entity: 'field-of-studies',
			items: [
				{ code: 36, name: 'Business Studies/Administration/Management' },
				{ code: 54, name: 'Commerce' },
				{ code: 15, name: 'Economics' },
				{ code: 28, name: 'Finance/Accountancy/Banking' },
				{ code: 30, name: 'Human Resource Management' },
				{ code: 49, name: 'Marketing' },
				{ code: 51, name: 'Secretarial' },
			],
		},
	},
	{
		code: 4,
		name: 'Services',
		children: {
			entity: 'field-of-studies',
			items: [
				{ code: 5, name: 'Airline Operation/Airport Management' },
				{ code: 27, name: 'Food & Beverage Services Management' },
				{ code: 10, name: 'Journalism' },
				{ code: 33, name: 'Library Management' },
				{ code: 35, name: 'Logistic/Transportation' },
				{ code: 41, name: 'Maritime Studies' },
				{ code: 47, name: 'Personal Services' },
				{ code: 111, name: 'Property Development/Real Estate Management' },
				{ code: 48, name: 'Protective Services & Management' },
			],
		},
	},
	{
		code: 5,
		name: 'Media/Art',
		children: {
			entity: 'field-of-studies',
			items: [
				{ code: 2, name: 'Advertising/Media' },
				{ code: 1, name: 'Art/Design/Creative Multimedia' },
				{ code: 32, name: 'Humanities/Liberal Arts' },
				{ code: 34, name: 'Linguistics/Languages' },
				{ code: 37, name: 'Mass Communications' },
				{ code: 42, name: 'Music/Performing Arts Studies' },
				{ code: 52, name: 'Textile/Fashion Design' },
			],
		},
	},
	{
		code: 6,
		name: 'Medicine',
		children: {
			entity: 'field-of-studies',
			items: [
				{ code: 9, name: 'Dentistry' },
				{ code: 40, name: 'Medical Science' },
				{ code: 39, name: 'Medicine' },
				{ code: 43, name: 'Nursing' },
				{ code: 45, name: 'Pharmacy/Pharmacology' },
				{ code: 109, name: 'Physical Therapy/Physiotherapy' },
				{ code: 112, name: 'Psychology' },
				{ code: 53, name: 'Veterinary' },
			],
		},
	},
	{
		code: 7,
		name: 'Others',
		children: {
			entity: 'field-of-studies',
			items: [
				{ code: 4, name: 'Architecture' },
				{ code: 17, name: 'Education/Teaching/Training' },
				{ code: 29, name: 'Hospitality/Tourism/Hotel Management' },
				{ code: 31, name: 'Law' },
				{ code: 44, name: 'Others' },
				{ code: 115, name: 'Urban Studies/Town Planning' },
			],
		},
	},
];

export const fieldStudies = fieldStudiesData.map(val => ({
	label: val.name,
	value: val.name,
}));

export const yearOfStudies = [
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	8,
	9,
	10,
	11,
	12,
	13,
	14,
	15,
	16,
	17,
	18,
	19,
	20,
	21,
	22,
	23,
	24,
	'More than 24',
].map(val => ({
	label: val,
	value: val,
}));
